name: Playwright Client Vulnerability Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  client-vulnerability-test:
    name: Run Client Vulnerability test (Playwright)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Client Vulnerability test with Allure
        run: |
          npx playwright test tests/about_page/client_vulnerability.spec.js --reporter=list,allure-playwright

      - name: Upload Allure results (Client Vulnerability)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-client-vulnerability
          path: allure-results
          retention-days: 30




  # playground-main:
  #   name: Run Main page tests (Playwright)
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.18.0
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #
  #     - name: Run Main tests with Allure
  #       run: |
  #         npm run test:main -- --reporter=list,allure-playwright
  #
  #     - name: Upload Allure results (Main)
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: allure-results-main
  #         path: allure-results
  #         retention-days: 30

