name: Playwright Complaints Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  complaints-test:
    name: Run Complaints Test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # 5️⃣ Run the test
      - name: Run complaints.spec.js
        run: npx playwright test tests/about_page/complaints.spec.js --reporter=list,allure-playwright --retries=2

      # 6️⃣ Upload test results for Allure
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: playwright-report








  # playground-main:
  #   name: Run Main page tests (Playwright)
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.18.0
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #
  #     - name: Run Main tests with Allure
  #       run: |
  #         npm run test:main -- --reporter=list,allure-playwright
  #
  #     - name: Upload Allure results (Main)
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: allure-results-main
  #         path: allure-results
  #         retention-days: 30

