name: Playwright About Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  about-tests:
    name: Run About Section Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.18.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run About tests
        run: |
          npx playwright test tests/about_page \
            --reporter=list,allure-playwright \
            --retries=2

      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report









  # playground-main:
  #   name: Run Main page tests (Playwright)
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.18.0
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #
  #     - name: Run Main tests with Allure
  #       run: |
  #         npm run test:main -- --reporter=list,allure-playwright
  #
  #     - name: Upload Allure results (Main)
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: allure-results-main
  #         path: allure-results
  #         retention-days: 30

